progenitor(jose,joao).
progenitor(jose,ana).
progenitor(maria,joao).
progenitor(maria,ana).
progenitor(ana,helena).
progenitor(ana,joana).
progenitor(joao,mario).
progenitor(helena,carlos).
progenitor(mario,carlos).
sexo(masculino,jose).
sexo(masculino,joao).
sexo(feminino,ana).
sexo(feminino,maria).
sexo(feminino,helena).
sexo(feminino,joana).
sexo(masculino,mario).
sexo(masculino,carlos).
irma(ana,joao).
irma(joana,helena).
irma(helena,joana).
irmao(joao,ana).
descendente(carlos,mario).
descendente(carlos,helena).
descendente(mario,joao).
descendente(joao,jose).
descendente(joao,maria).
descendente(helena,ana).
descendente(joana,ana).
descendente(ana,jose).
descendente(ana,maria).
mae(maria,joao).
mae(maria,ana).
mae(ana,joana).
mae(ana,helena).
mae(helena,carlos).
pai(jose,joao).
pai(jose,ana).
pai(joao,mario).
pai(mario,carlos).
avo(joao,carlos).
avo(jose,mario).
avo(jose,helena).
avo(jose,joana).
tio(joao,joana).
tio(joao,helena).
primo(mario,joana).
primo(mario,helena).
primo(joana,mario).
primo(helena,mario).